### ISSUE TITLE
Update BiRefNet model config for transformers 4.56+ compatibility

### ISSUE THREAD

**Issue by kyamagu** [CyberAgentAILab/LayerD#16]
## Issue

The LayerD BiRefNet model (`cyberagent/layerd-birefnet`) is incompatible with transformers 4.56+ due to a missing `is_encoder_decoder` attribute in the custom Config class.

## Root Cause

Starting from transformers 4.56, the `tie_weights()` method calls `get_text_config()` which expects all config objects to have an `is_encoder_decoder` attribute. Custom model configs loaded with `trust_remote_code=True` that don't define this attribute fail during model loading.

## Error

```python
AttributeError: 'Config' object has no attribute 'is_encoder_decoder'
```

Full traceback:
```
File "transformers/modeling_utils.py", line 4974, in from_pretrained
    model.tie_weights()
File "transformers/modeling_utils.py", line 3018, in tie_weights
    module.tie_embeddings_and_encoder_decoder()
File "transformers/modeling_utils.py", line 2994, in tie_embeddings_and_encoder_decoder
    if getattr(self.config.get_text_config(decoder=True), "tie_word_embeddings", True):
File "transformers/configuration_utils.py", line 1241, in get_text_config
    if not return_both and len(valid_text_config_names) == 0 and config_to_return.is_encoder_decoder:
File "transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'Config' object has no attribute 'is_encoder_decoder'
```

## Minimal Reproduction

```python
from transformers import AutoModelForImageSegmentation

# Works in transformers 4.55.4, fails in 4.56+
model = AutoModelForImageSegmentation.from_pretrained(
    'cyberagent/layerd-birefnet',
    trust_remote_code=True,
    device_map='cpu'
)
```

## Solution

Update the BiRefNet model's `Config` class in the HuggingFace repository to include:

```python
class Config:
    # ... existing attributes ...
    is_encoder_decoder = False  # Add this line
```

## Temporary Workaround

Currently pinned to `transformers>=4.55.4,<4.56` in pyproject.toml (see commit history).

## Impact

- Blocks upgrading to transformers 4.56+ which includes bug fixes and new features
- Affects all users of the LayerD BiRefNet model

## Related

- Transformers v4.56.0 release notes: https://github.com/huggingface/transformers/releases/tag/v4.56.0
- BiRefNet model: https://huggingface.co/cyberagent/layerd-birefnet

**Comment by kyamagu** [comment]
## Test Results with Commit e60c69e

Tested with transformers 4.57.3 and the updated HuggingFace config at commit `e60c69e`.

### ❌ Still Failing

The fix in `BiRefNet_config.py` is not sufficient. The error still occurs:

```
AttributeError: 'Config' object has no attribute 'is_encoder_decoder'
```

### Root Cause

The model is actually using the **`Config` class from `birefnet.py`**, not `BiRefNetConfig` from `BiRefNet_config.py`. 

Looking at the traceback, the config object type is `Config` (not `BiRefNetConfig`), which means the model instantiation uses the larger Config class defined in birefnet.py.

### Additional Fix Required

The `Config` class in **`birefnet.py`** also needs to be updated. Add this line at the beginning of the `__init__` method:

```python
class Config(PretrainedConfig):
    def __init__(self) -> None:
        # Add this line first
        self.is_encoder_decoder = False
        
        # PATH settings
        self.sys_home_dir = os.path.expanduser('~')
        # ... rest of existing code
```

Or as a class attribute:

```python
class Config(PretrainedConfig):
    is_encoder_decoder = False  # Add this class attribute
    
    def __init__(self) -> None:
        # PATH settings
        self.sys_home_dir = os.path.expanduser('~')
        # ... rest of existing code
```

### Files That Need Updates

1. ✅ `BiRefNet_config.py` - Already updated in e60c69e
2. ❌ `birefnet.py` - **Still needs the fix** for the `Config` class

**Comment by kyamagu** [comment]
## ✅ RESOLVED: Transformers 4.56+ Compatibility Confirmed

### Test Results with Merged Changes

**Environment:**
- transformers: 4.57.3
- BiRefNet: main branch (with merged fixes)

### Model Loading: ✅ SUCCESS
```
✅ Model loaded from main branch with transformers 4.57.3!
Model type: BiRefNet
Config type: Config
Has is_encoder_decoder: True
is_encoder_decoder value: False
```

### Full Test Suite: ✅ ALL TESTS PASSED
```
tests/test_basic_decompose.py::test_decompose[False-False] PASSED
tests/test_basic_decompose.py::test_decompose[False-True] PASSED
tests/test_basic_decompose.py::test_decompose[True-False] PASSED
tests/test_basic_decompose.py::test_decompose[True-True] PASSED

4 passed in 112.75s
```

### Changes Made

**pyproject.toml:**
- Removed `<4.56` version constraint
- Now using `transformers>=4.55.4` (allows 4.56+)

**HuggingFace Repository (cyberagent/layerd-birefnet):**
- Updated `BiRefNet_config.py` to include `is_encoder_decoder` attribute
- Updated `Config` class in `birefnet.py` to include `is_encoder_decoder` attribute

### Summary

The compatibility issue with transformers 4.56+ is now fully resolved! The BiRefNet model works correctly with the latest transformers version (4.57.3), and all tests pass successfully.

Thanks for the quick fix on the HuggingFace repository! 🚀
